print("""--------------CONVERSOR DE MINUTOS EM HORAS------------------
""")
minutos = int(input("Digite quantos minutos se passaram: ",))
horas = minutos/60
print("""..........
..........
..........
CALCULANDO
..........
..........
..........""")
print("RESULTADO:",minutos,"Minutos, equivalem a:",horas,"Horas")
